//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "card_keys")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub key_id: i32,
    #[sea_orm(unique)]
    pub card_key: String,
    pub r#type: String,
    pub value: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub activated_at: Option<DateTimeUtc>,
    pub expires_at: Option<DateTimeUtc>,
    pub is_active: Option<i8>,
    pub authorization_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
