//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::announcements::Entity as Announcements;
pub use super::card_keys::Entity as CardKeys;
pub use super::computer_authorizations::Entity as ComputerAuthorizations;
pub use super::computers_id_log::Entity as ComputersIdLog;
pub use super::user_ip_logs::Entity as UserIpLogs;
pub use super::users::Entity as Users;
